# Generated by Django 5.2.5 on 2025-09-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.GenericIPAddressField()),
                ('max_channels', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.PositiveIntegerField()),
                ('rtsp_url', models.CharField(max_length=255)),
                ('dvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='data.dvr')),
            ],
        ),
    ]
